# This file was *autogenerated* from the file 2-cell-2-cuts.sage
from sage.all_cmdline import *   # import sage library
print """
This program will run indefinitely, counting the number of graphs
that can be embedded on the n-torus in such a way that the surface
is separated into two cellular faces, neither of which border them-
selves.

It will also save each set of graphs as a compressed Sage object
in the current directory.

Finally, it is has been optimized to run in parallel on your """ + str(sage.parallel.ncpus.ncpus()) + " cores.\n"

import sys

@parallel
def build_children(seedGraph):
    def pick_v(g):
        #given a g, returns all possible (graph, picked v) in a  list
        newGraphs = []
        for edge in g.edges():
            h = g.copy()
            startv = edge[Integer(0)]
            endv = edge[Integer(1)]
            h.delete_edge(edge)
            pickedV = h.add_vertex()
            h.add_edge(startv, pickedV)
            h.add_edge(pickedV, endv)
            yield (h, pickedV)
        for pickedV in g.vertices():
            h = g.copy()
            yield (h, pickedV)

    mutableG = seedGraph.copy(immutable = False)
    childSet = set()
    
    for tempGraph, firstV in pick_v(mutableG):
        for finalGraph, secondV in pick_v(tempGraph):
            finalGraph.add_edges([(firstV,secondV),(firstV,secondV)])
            setMember = finalGraph.canonical_label().copy(immutable=True)
            childSet.add(setMember)
    
    return childSet

def next_genus(seeds, verbose = False):
    #if verbose is True this function will
    #keep us updated on how many graphs have been found
    
    completeSet = set()
    completeSetLength = Integer(0)
    
    if verbose:
        for output in build_children(seeds):
            completeSet.update(output[Integer(1)])
            sys.stdout.write("\r{} graphs...".format(len(completeSet)))
            sys.stdout.flush()
    else:
        for output in build_children(seeds):
            completeSet.update(output[Integer(1)])

    if verbose:
        sys.stdout.write("\r{} graphs - done!".format(len(completeSet)))
        
    return list(completeSet)

g = Graph({Integer(0):[Integer(0),Integer(0),Integer(0)]})
g.allow_loops(True)
g.allow_multiple_edges(True)

h = Graph({Integer(0):[],Integer(1):[Integer(0),Integer(0),Integer(0),Integer(0)]})
h.allow_loops(True)
h.allow_multiple_edges(True)

currentSeeds = [g,h]
genusNum = Integer(1)
while True:
    nextGenusGraphs = next_genus(currentSeeds)
    genusNum += Integer(1)
    save(nextGenusGraphs, './genus_'+str(genusNum)+'_graphs')
    print "There are", len(nextGenusGraphs), "graphs for genus", genusNum
    currentSeeds = nextGenusGraphs
